name = "coldblog"
compatibility_date = "2025-08-08"
pages_build_output_dir = "./dist"

[build]
command = "bun install && bun run build"
cwd = "."

[build.environment]
BUN_VERSION = "1.2.21"
SKIP_INSTALL_DEPS = "true"
